apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: team-finance
  source:
    repoURL: 'https://github.com/vinnie-kaboom/argocd-example-apps-1.git'
    path: helm-guestbook
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: finance
