apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-finance
  namespace: argocd
spec:
  description: Project for Team Finance with security guardrails

  sourceRepos:
    - 'https://github.com/vinnie-kaboom/argocd-example-apps-1.git'

  destinations:
    - server: https://kubernetes.default.svc
      namespace: finance

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'