apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-project
  namespace: argocd
spec:
  description: Demo project for canary rollout learning
  sourceRepos:
    - 'https://github.com/vinnie-kaboom/argo_cd_demo.git'
  destinations:
    - namespace: 'demo-*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'