apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-app:9d0b232
          ports:
            - containerPort: 80
              protocol: TCP
  strategy:
    canary:
      steps:
        - setWeight: 100
