apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/vinnie-kaboom/my-app.git
      targetRevision: HEAD
      path: helm
      helm:
        valueFiles:
          - helm/values.yaml
    - repoURL: https://github.com/vinnie-kaboom/my-app.git
      targetRevision: HEAD
      path: apps/app/my-app/external-secrets/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
