apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/vinnie-kaboom/my-app.git
      targetRevision: HEAD
      path: helm
      helm:
        valueFiles:
          - $values/apps/my-app/deploy/overlays/prod/values.yaml
    - repoURL: https://github.com/vinnie-kaboom/argo_cd_demo.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/vinnie-kaboom/argo_cd_demo.git
      targetRevision: HEAD
      path: apps/my-app/external-secrets/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
