image:
  repository: vincentzamora123/my-app
  tag: "9d0b232"
  pullPolicy: IfNotPresent
  pullSecrets: []

replicaCount: 3

config:
  PORT: "8080"
  LOG_LEVEL: warn
  ENVIRONMENT: staging
  APP_COLOR: gold
  DEMO_BANNER: STAGING PIPELINE - CHANGE ME

secret:
  create: false

canary:
  steps:
    - setWeight: 10
    - pause: {}
    - setWeight: 30
    - pause:
        duration: 1m
    - setWeight: 60
    - pause:
        duration: 1m

pdb:
  enabled: false
