# Development overlay – fast iteration
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: my-app-dev
images:
  - name: my-app
    # The username below should be replaced by CI/CD automation using the DOCKERHUB_USERNAME secret
    newName: docker.io/vincentzamora123/my-app
    # The tag below should be set by automation (e.g., CI/CD or repository dispatch)
    # After dev is validated, this tag can be promoted to staging/prod overlays
    newTag: "9d0b232"
