image:
  repository: vincentzamora123/my-app
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

replicaCount: 2

config:
  PORT: "8080"
  LOG_LEVEL: debug
  ENVIRONMENT: dev

secret:
  create: false

canary:
  steps:
    - setWeight: 50
    - pause:
        duration: 30s
    - setWeight: 100

pdb:
  enabled: false
