apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - eventbus.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - workflow-template.yaml
  - eventsource.yaml
  - sensor.yaml
