apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-managed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.8.3
    helm:
      releaseName: argocd
      values: |
        server:
          service:
            type: NodePort
        configs:
          params:
            server.insecure: true
        dex:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
